### ISSUE TITLE
soz-upw GetPollutionLevel error

### ISSUE THREAD

**Issue by TRLKO** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

Hi, after fresh install of soz i have error in resource soz-upw in server/main.lua:188. Bellow I send console log

`[      script:oxmysql] Database server connection established!
[38;5;196m[      script:soz-upw] SCRIPT ERROR: @soz-upw/server/main.lua:188: attempt to call a nil value (method 'GetPollutionLevel')
[      script:soz-upw] > ref (@soz-upw/server/main.lua:188)
[      script:soz-upw] > Tc.onTick (@soz-core/build/server.js:2)
[      script:soz-upw] > <unknown> (@soz-core/build/server.js:2)
[      script:soz-upw] > <unknown> ([36m@soz-core/build/server.js:2)
[     script:soz-core] Error: Error in monitor:upw:metrics Error: An error occurred while calling export GetMetrics of resource soz-upw - see above for details
[     script:soz-core]     at Proxy.<anonymous> (citizen:/scripting/v8/main.js:557:15)
[     script:soz-core]     at Tc.onTick (@soz-core/build/server.js:2:1428382)
[     script:soz-core]     at @soz-core/build/server.js:2:1126400
[     script:soz-core]     at @soz-core/build/server.js:2:1127789
[     script:soz-core]     at Object.callback (@soz-core/build/server.js:2:1117533)
[     script:soz-core]     at onTick (citizen:/scripting/v8/timer.js:192:33)
[     script:soz-core]     at citizen:/scripting/v8/timer.js:270:13
[     script:soz-core]     at Number.__cfx_wrap_250 (citizen:/scripting/v8/main.js:23:12)
[     script:soz-core]     at citizen:/scripting/v8/main.js:29:16
[     script:soz-core]     at citizen:/scripting/v8/timer.js:269:16
[      script:monitor] [txAdminClient] Threads and commands set up. All Ready.
[     script:soz-core] [4.05.2023, 10:15:03] [Prisma] [quaint::pooled] Starting a mysql pool with 13 connections.
[     script:soz-core] [4.05.2023, 10:15:03] [Prisma] [query_engine::server] Started query engine http server on http://127.0.0.1:56248
(node:6880) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use FXServer --trace-warnings ... to show where the warning was created)`

### Reproduction Steps

Just only start a server.

### Does it happen all the time ?

100% of the time

**Comment by TRLKO** [comment]
Hi @NariieL the problem still exist and issue isn’t resolved
